name: Build Typecho Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Typecho version'
        required: true

jobs:
  build_80_apache_debian:
    concurrency: build_debian_80
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Dockerfile
        id: generate
        run: |
          ./build.sh -g -v ${{ github.event.inputs.version }} -p 8.0 -o debian apache
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ steps.generate.outputs.PLATFORM }}
          push: true
          tags: ${{ steps.generate.outputs.VERSION }}
          build-args: |
            TAG=${{ steps.generate.outputs.TAG }}
            URL=${{ steps.generate.outputs.URL }}
            CONFIG=${{ steps.generate.outputs.CONFIG }}
            PHP_EXTENSION=${{ steps.generate.outputs.PHP_EXTENSION }}
            PHP8_SOCKETS_WORKAROUND=${{ steps.generate.outputs.PHP8_SOCKETS_WORKAROUND }}
          cache-from: type=gha
          cache-to: type=gha,mode=max